# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GET_ERROR_TYPE <- function() {
    .Call(`_inplace_GET_ERROR_TYPE`)
}

GET_ERROR_DIM <- function() {
    .Call(`_inplace_GET_ERROR_DIM`)
}

GET_ERROR_BOUNDS <- function() {
    .Call(`_inplace_GET_ERROR_BOUNDS`)
}

GET_ERROR_FATAL <- function() {
    .Call(`_inplace_GET_ERROR_FATAL`)
}

multiply_all_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_all_mult`, x, i, j, val))
}

multiply_subvec_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_subvec_mult`, x, i, j, val))
}

multiply_submat_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_submat_mult`, x, i, j, val))
}

multiply_all_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_all_one`, x, i, j, val))
}

multiply_subvec_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_subvec_one`, x, i, j, val))
}

multiply_submat_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_submat_one`, x, i, j, val))
}

