# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_all_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_add_all_mult`, x, i, j, val))
}

add_subvec_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_add_subvec_mult`, x, i, j, val))
}

add_submat_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_add_submat_mult`, x, i, j, val))
}

add_all_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_add_all_one`, x, i, j, val))
}

add_subvec_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_add_subvec_one`, x, i, j, val))
}

add_submat_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_add_submat_one`, x, i, j, val))
}

add_sweep1 <- function(x, val) {
    invisible(.Call(`_inplace_add_sweep1`, x, val))
}

add_sweep2 <- function(x, val) {
    invisible(.Call(`_inplace_add_sweep2`, x, val))
}

divide_all_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_divide_all_mult`, x, i, j, val))
}

divide_subvec_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_divide_subvec_mult`, x, i, j, val))
}

divide_submat_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_divide_submat_mult`, x, i, j, val))
}

divide_all_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_divide_all_one`, x, i, j, val))
}

divide_subvec_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_divide_subvec_one`, x, i, j, val))
}

divide_submat_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_divide_submat_one`, x, i, j, val))
}

divide_sweep1 <- function(x, val) {
    invisible(.Call(`_inplace_divide_sweep1`, x, val))
}

divide_sweep2 <- function(x, val) {
    invisible(.Call(`_inplace_divide_sweep2`, x, val))
}

GET_ERROR_TYPE <- function() {
    .Call(`_inplace_GET_ERROR_TYPE`)
}

GET_ERROR_DIM <- function() {
    .Call(`_inplace_GET_ERROR_DIM`)
}

GET_ERROR_BOUNDS <- function() {
    .Call(`_inplace_GET_ERROR_BOUNDS`)
}

GET_ERROR_FATAL <- function() {
    .Call(`_inplace_GET_ERROR_FATAL`)
}

multiply_all_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_all_mult`, x, i, j, val))
}

multiply_subvec_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_subvec_mult`, x, i, j, val))
}

multiply_submat_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_submat_mult`, x, i, j, val))
}

multiply_all_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_all_one`, x, i, j, val))
}

multiply_subvec_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_subvec_one`, x, i, j, val))
}

multiply_submat_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_multiply_submat_one`, x, i, j, val))
}

multiply_sweep1 <- function(x, val) {
    invisible(.Call(`_inplace_multiply_sweep1`, x, val))
}

multiply_sweep2 <- function(x, val) {
    invisible(.Call(`_inplace_multiply_sweep2`, x, val))
}

substract_all_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_substract_all_mult`, x, i, j, val))
}

substract_subvec_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_substract_subvec_mult`, x, i, j, val))
}

substract_submat_mult <- function(x, i, j, val) {
    invisible(.Call(`_inplace_substract_submat_mult`, x, i, j, val))
}

substract_all_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_substract_all_one`, x, i, j, val))
}

substract_subvec_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_substract_subvec_one`, x, i, j, val))
}

substract_submat_one <- function(x, i, j, val) {
    invisible(.Call(`_inplace_substract_submat_one`, x, i, j, val))
}

substract_sweep1 <- function(x, val) {
    invisible(.Call(`_inplace_substract_sweep1`, x, val))
}

substract_sweep2 <- function(x, val) {
    invisible(.Call(`_inplace_substract_sweep2`, x, val))
}

